version: "3"
services:
  auth:
    image: jainendrakumar10/auth2:latest
    ports:
      - 7998:5000
    deploy:
      replicas: 3
      update_config:
        parallelism: 3
        delay: 10s
      restart_policy:
        condition: on-failure
